### PR TITLE
fix: re-enable flask multi-threading

### PR DESCRIPTION
**Pull request by ShootingKing-AM**
To solve issue: https://github.com/ActivityWatch/activitywatch/issues/773

### CODE REVIEW

**Comment by ShootingKing-AM** [comment]
@ErikBjare meow?

**Comment by ErikBjare** [comment]
I'm worried this might have unintended side-effects (cause race-conditions in heartbeats etc), so a bit hesitant to merge this.

Hopefully some test would fail if that's the case, but for some reason it seems that CI hasn't run on this PR?

**Comment by ShootingKing-AM** [comment]
It seems to be waiting for approval, you can also re run workflow manually

**Comment by ErikBjare** [comment]
Must've been some bug in the GitHub mobile UI, approved now :)

**Comment by ErikBjare** [comment]
Alright, merged #95 so now I'm less worried about thread safety.

Merging :)

**Pull request merged**
