### PR TITLE
Cache last event to improve heartbeat performance

### PR DESCRIPTION
**Pull request by ErikBjare**
My aw-server instance is taking a bit too much CPU for my taste. This was an attempt at alleviating a database query that could easily be cached.

This should probably not make it into v0.7

### CODE REVIEW

**Comment by ErikBjare** [comment]
A few things:

 - I don't think the performance improvements are that great. We should do proper profiling instead.
 - Haven't done any testing what happens when events are received out of order. Might cause issues. 
 - Only speeds up the case where an event is received immediately.
 - It's a bit hacky, not very happy about how complex it turned out.

**Comment by ErikBjare** [comment]
Did a little benchmarking, appears to increase performance by about 25% in my "every third event is different" test.

**Comment by ErikBjare** [comment]
That last commit lead to an additional performance improvement, now at ~33%.

**Comment by johan-bjareholt** [comment]
To this PR we could also add a feature which waits to write to disk until either 

1. The data changes (new heartbeat)
2. It was more than X seconds since last DB write (5-30s? configurable in config maybe?)

This would lower IO read/writes significantly which should improve HDD lifespan and avoid waking up a HDD which is suspended which will likely improve battery life very so slightly on laptops with a HDD.

**Comment by ErikBjare** [comment]
Closing in favor of https://github.com/ActivityWatch/aw-server/pull/46

**Pull request closed without merging**
