### PR TITLE
Added dat:// protocol as allowed CORS origin

### PR DESCRIPTION
**Pull request by staltz**
Hi! Thanks for ActivityWatch, I started using it a few days ago and find it useful.

I wanted to use the REST API to create my custom visualizations as frontend web apps (to run always locally), and noticed that I couldn't use the aw-server REST because of CORS issues. It would be nice if this would be an easy use case, even though I read that the HTTP interface shouldn't be used directly.

This PR adds a simple support for dat://* origins, similarly to moz-extension://*. Dat is a protocol used in [Beaker Browser](https://beakerbrowser.com/), which is a fantastic browser and really well suited for sharing local-only webapps, such as visualizations for AW.

dat:// is also supported in [Firefox](https://blog.mozilla.org/addons/2018/01/26/extensions-firefox-59/). When it comes to security, it's essentially like file:// (which should also be supported by aw-server?), because the files being fetched are always in the local machine.

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
Looks sane, file:// would also be nice to add. I've heard and read about dat but have never tried it so have zero experience with it.

Are dat:// webpages unable to communicate with remote servers? For example is it possible for javascript on a webpage received over dat to post data to a remote server?

**Comment by staltz** [comment]
That's a good question. I'm not the best at web security, but it seems to me that dat:// websites in Beaker are *able* to communicate with remote servers, see https://github.com/beakerbrowser/beaker/issues/95
How about `moz-extension://*`? Are they also able to?

That said, for my own purposes `file://` would be enough

**Comment by ErikBjare** [comment]
Hi @staltz, amazing to see you here (I'm a fan) 🤩

I'm not confident enough security-wise to add `dat://` (even if I think dat is amazing), and maybe not even `file://` since you'd just have to make someone open an `.html` file in order to steal *all* of the data. I'm therefore not very confident in adding any of them, sorry.

But there could be a command line argument for adding specific CORS origins. That would solve your problem nicely without adding security risk in the defaults.

**Comment by ErikBjare** [comment]
Regarding `moz-extensions://*` it might as well be a bit unsafe right now. You set permissions in the [manifest here](https://github.com/ActivityWatch/aw-watcher-web/blob/master/manifest.js). We should set stricter defaults, only whitelisting certain specific `moz-extensions://` (and equivalently for Chrom(e/ium).

**Comment by ErikBjare** [comment]
@staltz I can certainly see your dilemma, I only recently stopped paying for RescueTime myself.

Regarding the `moz-extensions://` thing it turns out [there was already a comment mentioning it](https://github.com/ActivityWatch/aw-server/blob/5a6b1c62fb5b898eca4289a60b783e1c1f5e1a72/aw_server/server.py#L48). I'll look into that later.

Since I certainly want to encourage development of frondend tools for visualization and stuff, I implemented the `--cors-origins` argument here: https://github.com/ActivityWatch/aw-server/pull/44

Have fun! And let us know about whatever you build :heart:

**Pull request closed without merging**
