### PR TITLE
Added errormsg from query2 exceptions to payload

### PR DESCRIPTION
**Pull request by johan-bjareholt**
Needs https://github.com/ActivityWatch/aw-core/pull/53 for new exception types

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
Tests breaks due to running master aw-core instead of https://github.com/ActivityWatch/aw-core/pull/53

**Comment by ErikBjare** [comment]
Alright, so if all the tests are passing then it all looks good!

**Comment by johan-bjareholt** [comment]
Didn't test locally before but did now, the aw_server tests were incredibly slow but everything passed.

**Comment by ErikBjare** [comment]
Then merge the aw-core stuff, restart the Travis builds, and merge when they pass :+1:

**Comment by johan-bjareholt** [comment]
Apparently "make test" which is used in travis doesn't run the tests/test_client.py tests but only imports aw_server and runs mypy.

**Comment by ErikBjare** [comment]
@johan-bjareholt Right, but they are ran in the bundle repo: https://github.com/ActivityWatch/activitywatch/blob/master/Makefile#L85

**Pull request merged**
